### ISSUE TITLE
[Feature] Better GUI

### ISSUE THREAD

**Issue by JonathanHoshi** [AY2122S2-CS2103T-T09-3/tp#74]
## Details
Modify Trackermon basic GUI to look better.

### [GUI template] _(designed by @aweijun)_
<img width="434" alt="Ui" src="https://user-images.githubusercontent.com/28040511/157698416-59a45f38-7c6c-4ea4-951a-1b920edbb80b.png">

### Task Done
- [ ] Add a UI section to display selected Shows (ShowDetailsCard)
- [ ] Update GUI layout to look like design by @aweijun 
- [ ] Made Trackermon selects the first show when list is not empty

### [Finalized GUI]
![Screenshot 2022-03-22 235149](https://user-images.githubusercontent.com/28040511/159522857-9c24277b-8cb2-4731-aa0f-cb52bb1c5e87.png)
